# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学员信息', 'verbose_name_plural': '学员信息'},
        ),
    ]
